namespace PlantBreeding.Localization
{
    /// <summary>
    /// Таблиця перекладів: (українською — як у коді/сценах, English, Polski).
    /// {0},{1}… — місця для чисел/назв (перекладаються рекурсивно).
    /// Нова фраза в грі → додати рядок сюди; без перекладу текст лишається українським
    /// (у редакторі LocalizationApplier пише такі тексти в консоль).
    /// </summary>
    public static class LocTable
    {
        public static readonly (string uk, string en, string pl)[] Entries =
        {
            // ── Навігація, шапка, заголовки ───────────────────────────────
            ("Сад", "Garden", "Ogród"),
            ("Лабораторія", "Laboratory", "Laboratorium"),
            ("Дендрарій", "Arboretum", "Arboretum"),
            ("Крамниця", "Shop", "Sklep"),
            ("Мій сад", "My garden", "Mój ogród"),
            ("Посадка", "Planting", "Sadzenie"),
            ("Дослідження", "Research", "Badania"),
            ("Колекції", "Collections", "Kolekcje"),
            ("ростуть", "growing", "rośnie"),
            ("готові", "ready", "gotowe"),
            ("РІВЕНЬ {0} · {1}/{2} XP", "LEVEL {0} · {1}/{2} XP", "POZIOM {0} · {1}/{2} XP"),
            ("РІВЕНЬ {0}", "LEVEL {0}", "POZIOM {0}"),

            // ── Налаштування ─────────────────────────────────────────────
            ("Налаштування", "Settings", "Ustawienia"),
            ("Тема", "Theme", "Motyw"),
            ("ТЕМА", "THEME", "MOTYW"),
            ("Мова", "Language", "Język"),
            ("МОВА", "LANGUAGE", "JĘZYK"),
            ("Темна", "Dark", "Ciemny"),
            ("Світла", "Light", "Jasny"),
            ("Як у системі", "System", "Systemowy"),

            // ── Грядка ───────────────────────────────────────────────────
            ("Посадити", "Plant", "Posadź"),
            ("Заблоковано", "Locked", "Zablokowane"),
            ("Росте", "Growing", "Rośnie"),
            ("Готово", "Ready", "Gotowe"),
            ("Полити", "Water", "Podlej"),
            ("Рослина", "Plant", "Roślina"),
            ("Рівень {0}\nабо {1} монет", "Level {0}\nor {1} coins", "Poziom {0}\nlub {1} monet"),
            ("Рівень {0}", "Level {0}", "Poziom {0}"),
            ("Зібрати все · {0}", "Harvest all · {0}", "Zbierz wszystko · {0}"),
            ("{0} год {1} хв", "{0} h {1} min", "{0} godz. {1} min"),
            ("{0} год", "{0} h", "{0} godz."),
            ("{0} хв", "{0} min", "{0} min"),
            ("{0} с", "{0} s", "{0} s"),
            ("<1 хв", "<1 min", "<1 min"),

            // ── Рослини ──────────────────────────────────────────────────
            ("Фіалка", "African violet", "Fiołek afrykański"),
            ("Кактус", "Cactus", "Kaktus"),
            ("Алое", "Aloe", "Aloes"),
            ("Хлорофітум", "Spider plant", "Zielistka"),
            ("Сансев'єрія", "Snake plant", "Sansewieria"),
            ("Заміокулькас", "ZZ plant", "Zamiokulkas"),
            ("Епіпремнум", "Pothos", "Epipremnum"),
            ("Спатифілум", "Peace lily", "Skrzydłokwiat"),
            ("Фікус Бенджаміна", "Weeping fig", "Figowiec benjamina"),
            ("Бегонія", "Begonia", "Begonia"),
            ("Калатея", "Calathea", "Kalatea"),
            ("Пеларгонія", "Geranium", "Pelargonia"),
            ("Антуріум", "Anthurium", "Anturium"),
            ("Монстера", "Monstera", "Monstera"),
            ("Гібіскус", "Hibiscus", "Hibiskus"),
            ("Азалія", "Azalea", "Azalia"),
            ("Фікус ліровидний", "Fiddle-leaf fig", "Figowiec dębolistny"),
            ("Гарденія", "Gardenia", "Gardenia"),
            ("Стреліція", "Bird of paradise", "Strelicja"),
            ("Орхідея", "Orchid", "Storczyk"),

            // ── Горщики ──────────────────────────────────────────────────
            ("Пластиковий", "Plastic", "Plastikowa"),
            ("Теракотовий", "Terracotta", "Terakotowa"),
            ("Керамічний", "Ceramic", "Ceramiczna"),
            ("Плетене кашпо", "Wicker basket", "Wiklinowa osłonka"),
            ("Бетонний", "Concrete", "Betonowa"),
            ("Латунний", "Brass", "Mosiężna"),
            ("Мармуровий", "Marble", "Marmurowa"),
            ("без бонусу", "no bonus", "bez bonusu"),
            ("{0}% часу росту", "{0}% grow time", "{0}% czasu wzrostu"),
            ("полив рідше на {0}%", "water {0}% less often", "podlewanie o {0}% rzadziej"),
            ("{0}% ціна продажу", "{0}% sell price", "{0}% ceny sprzedaży"),
            ("{0}% ціна", "{0}% price", "{0}% ceny"),
            ("{0}% хвороб", "{0}% diseases", "{0}% chorób"),

            // ── Посадка ──────────────────────────────────────────────────
            ("Оберіть рослину", "Choose a plant", "Wybierz roślinę"),
            ("Оберіть горщик", "Choose a pot", "Wybierz doniczkę"),
            ("Добриво", "Fertilizer", "Nawóz"),
            ("інвентар", "inventory", "ekwipunek"),
            ("останній обраний", "last used", "ostatnio wybrana"),
            ("опційно", "optional", "opcjonalnie"),
            ("Оберіть рослину для прогнозу", "Choose a plant to see the forecast", "Wybierz roślinę, aby zobaczyć prognozę"),
            ("год", "h", "godz."),
            ("монет", "coins", "monet"),
            ("базовий", "base", "bazowy"),
            ("з рівня {0}", "from level {0}", "od poziomu {0}"),
            ("×{0} насіння", "×{0} seeds", "×{0} nasion"),
            ("Купити · {0} монет", "Buy · {0} coins", "Kup · {0} monet"),
            ("<color=#{0}>Купити · {1}</color>", "<color=#{0}>Buy · {1}</color>", "<color=#{0}>Kup · {1}</color>"),
            ("Купити · {0}", "Buy · {0}", "Kup · {0}"),
            ("Лише зі схрещування", "Breeding only", "Tylko z krzyżowania"),
            ("Посадити {0}", "Plant: {0}", "Posadź: {0}"),
            ("{0}% модиф.", "{0}% mod.", "{0}% mod."),
            ("{0}% горщик", "{0}% pot", "{0}% doniczka"),
            ("+полив до 30%", "+watering up to 30%", "+podlewanie do 30%"),
            ("Без добрива", "No fertilizer", "Bez nawozu"),
            ("за замовчуванням", "default", "domyślnie"),
            ("Ріст-буст", "Grow boost", "Przyspieszacz"),
            ("-30% часу росту", "-30% grow time", "-30% czasu wzrostu"),
            ("{0} монет", "{0} coins", "{0} monet"),

            // ── Урожай, рівні, грядки (тости) ────────────────────────────
            ("{0}: +{1} монет (подвійний урожай!)", "{0}: +{1} coins (double harvest!)", "{0}: +{1} monet (podwójny plon!)"),
            ("{0}: +{1} монет (догляд +{2}%)", "{0}: +{1} coins (care +{2}%)", "{0}: +{1} monet (pielęgnacja +{2}%)"),
            ("{0}: +{1} монет", "{0}: +{1} coins", "{0}: +{1} monet"),
            ("Перший урожай! Бонус +{0} монет — купи нове насіння", "First harvest! Bonus +{0} coins — buy new seeds", "Pierwszy plon! Bonus +{0} monet — kup nowe nasiona"),
            ("Рівень {0}! +{1} монет", "Level {0}! +{1} coins", "Poziom {0}! +{1} monet"),
            ("нове насіння: {0}", "new seeds: {0}", "nowe nasiona: {0}"),
            ("нова грядка", "new plot", "nowa grządka"),
            ("Грядка відкриється на рівні {0}", "Plot unlocks at level {0}", "Grządka odblokuje się na poziomie {0}"),
            ("Потрібно {0} монет (або рівень {1})", "Need {0} coins (or level {1})", "Potrzeba {0} monet (lub poziom {1})"),
            ("Нову грядку відкрито!", "New plot unlocked!", "Nowa grządka odblokowana!"),
            ("Зібрано {0} {1}: +{2} монет", "Harvested {0} {1}: +{2} coins", "Zebrano {0} {1}: +{2} monet"),
            ("рослин", "plants", "roślin"),
            ("рослину", "plant", "roślinę"),
            ("рослини", "plants", "rośliny"),
            ("Полито! +{0}% до ціни врожаю", "Watered! +{0}% to harvest price", "Podlano! +{0}% do ceny plonu"),
            ("Тапни порожню грядку й посади фіалку — вона виросте за 3 хвилини",
                "Tap an empty plot and plant a violet — it grows in 3 minutes",
                "Dotknij pustej grządki i posadź fiołek — wyrośnie w 3 minuty"),

            // ── Прискорення ──────────────────────────────────────────────
            ("{0}: {1} → {2} (−{3} крист.)", "{0}: {1} → {2} (−{3} gems)", "{0}: {1} → {2} (−{3} kryszt.)"),
            ("Рослина дорастає в 10 разів швидше: лишається 10% часу. Один раз на посадку.",
                "The plant grows 10× faster: only 10% of the time remains. Once per planting.",
                "Roślina rośnie 10× szybciej: zostaje 10% czasu. Raz na sadzenie."),
            ("До врожаю: {0} → {1}", "Until harvest: {0} → {1}", "Do zbioru: {0} → {1}"),
            ("До врожаю: {0}", "Until harvest: {0}", "Do zbioru: {0}"),
            ("У тебе: {0} {1}", "You have: {0} {1}", "Masz: {0} {1}"),
            ("Уже прискорено", "Already sped up", "Już przyspieszono"),
            ("Прискорити ×10 · {0} {1}", "Speed up ×10 · {0} {1}", "Przyspiesz ×10 · {0} {1}"),
            ("Потрібно {0} {1} — купити", "Need {0} {1} — buy", "Potrzeba {0} {1} — kup"),
            ("кристалів", "gems", "kryształów"),
            ("кристал", "gem", "kryształ"),
            ("кристали", "gems", "kryształy"),

            // ── Крамниця ─────────────────────────────────────────────────
            ("Кристали прискорюють ріст рослини в 10 разів", "Gems make a plant grow 10× faster", "Kryształy przyspieszają wzrost rośliny 10×"),
            ("Тестовий режим: оплата ще не підключена, кристали нараховуються одразу.",
                "Test mode: payments are not connected yet, gems are added instantly.",
                "Tryb testowy: płatności nie są jeszcze podłączone, kryształy dodawane są od razu."),
            ("Оплата ще не підключена — Крамниця запрацює незабаром", "Payments are not connected yet — the Shop is coming soon", "Płatności nie są jeszcze podłączone — sklep wkrótce"),
            ("+{0} кристалів (тестова покупка, оплата не підключена)", "+{0} gems (test purchase, payments not connected)", "+{0} kryształów (zakup testowy, płatności niepodłączone)"),
            ("{0} грн", "UAH {0}", "{0} UAH"),
            ("вигідно", "best value", "opłacalne"),
            ("Закрити", "Close", "Zamknij"),

            // ── Хвороби й лікування ──────────────────────────────────────
            ("Тля", "Aphids", "Mszyce"),
            ("Павутинний кліщ", "Spider mites", "Przędziorki"),
            ("Борошниста роса", "Powdery mildew", "Mączniak"),
            ("Хлороз", "Chlorosis", "Chloroza"),
            ("Зелені крапки на листі. Прибери їх — тапай по листочках.", "Green dots on the leaves. Remove them — tap the leaves.", "Zielone kropki na liściach. Usuń je — stukaj w liście."),
            ("Павутинка між листками. Обприскай листя — тапай, поки не зникне.", "Webbing between the leaves. Spray the leaves — tap until it's gone.", "Pajęczyna między liśćmi. Spryskaj liście — stukaj, aż zniknie."),
            ("Білий наліт на листі — грибок. Потрібен фунгіцид.", "White coating on the leaves — a fungus. Needs a fungicide.", "Biały nalot na liściach — grzyb. Potrzebny fungicyd."),
            ("Листя жовтіє — бракує заліза. Потрібне залізне добриво.", "Leaves turn yellow — iron deficiency. Needs iron fertilizer.", "Liście żółkną — brakuje żelaza. Potrzebny nawóz żelazowy."),
            ("Фунгіцид", "Fungicide", "Fungicyd"),
            ("фунгіцид", "fungicide", "fungicyd"),
            ("Залізне добриво", "Iron fertilizer", "Nawóz żelazowy"),
            ("залізне добриво", "iron fertilizer", "nawóz żelazowy"),
            ("Поки рослина хворіє, вона не росте.", "While the plant is sick, it doesn't grow.", "Dopóki roślina choruje, nie rośnie."),
            ("Прибрати · ще {0} {1}", "Remove · {0} more {1}", "Usuń · jeszcze {0} {1}"),
            ("{0} · {1} монет", "{0} · {1} coins", "{0} · {1} monet"),
            ("{0}: потрібно {1} монет", "{0}: need {1} coins", "{0}: potrzeba {1} monet"),
            ("тапів", "taps", "stuknięć"),
            ("тап", "tap", "stuknięcie"),
            ("тапи", "taps", "stuknięcia"),
            ("{0}: прибрано! {1} знову росте", "{0}: removed! {1} is growing again", "{0}: usunięto! {1} znowu rośnie"),
            ("Потрібно {0} монет на {1}", "Need {0} coins for {1}", "Potrzeba {0} monet na {1}"),
            ("{0} подіяв — {1} знову росте (−{2} монет)", "{0} worked — {1} is growing again (−{2} coins)", "{0} zadziałał — {1} znowu rośnie (−{2} monet)"),

            // ── Завдання дня, вхід, скриня ───────────────────────────────
            ("Завдання дня", "Daily tasks", "Zadania dnia"),
            ("Завдання", "Task", "Zadanie"),
            ("Стрік входів: {0} дн. · нові завдання щодня опівночі", "Login streak: {0} d · new tasks every midnight", "Seria logowań: {0} dn. · nowe zadania co północ"),
            ("Заходь завтра — почнеться стрік щоденних нагород", "Come back tomorrow to start a daily reward streak", "Wróć jutro — zacznie się seria codziennych nagród"),
            ("Нагорода за вхід · день {0} з 7", "Login reward · day {0} of 7", "Nagroda za logowanie · dzień {0} z 7"),
            ("Завтра: {0}", "Tomorrow: {0}", "Jutro: {0}"),
            ("Отримано. Завтра: {0}", "Claimed. Tomorrow: {0}", "Odebrano. Jutro: {0}"),
            ("Завтра", "Tomorrow", "Jutro"),
            ("Забрати", "Claim", "Odbierz"),
            ("Отримано", "Claimed", "Odebrano"),
            ("В процесі", "In progress", "W toku"),
            ("Відкрити", "Open", "Otwórz"),
            ("Відкрито", "Opened", "Otwarto"),
            ("+{0} монет", "+{0} coins", "+{0} monet"),
            ("+{0} XP", "+{0} XP", "+{0} XP"),
            ("+{0} насіння «{1}»", "+{0} {1} seeds", "+{0} nasion: {1}"),
            ("Нагороду дня {0} отримано: {1}", "Day {0} reward claimed: {1}", "Nagroda dnia {0} odebrana: {1}"),
            ("Скриню дня відкрито. Нові завдання — завтра!", "Daily chest opened. New tasks tomorrow!", "Skrzynia dnia otwarta. Nowe zadania jutro!"),
            ("Скриня дня: виконай усі завдання → +{0} монет", "Daily chest: finish all tasks → +{0} coins", "Skrzynia dnia: wykonaj wszystkie zadania → +{0} monet"),
            ("Скриня дня: +{0} монет", "Daily chest: +{0} coins", "Skrzynia dnia: +{0} monet"),
            ("+{0} XP. Нові завдання — завтра!", "+{0} XP. New tasks tomorrow!", "+{0} XP. Nowe zadania jutro!"),
            ("Завдання виконано: {0} — забери нагороду", "Task complete: {0} — claim your reward", "Zadanie wykonane: {0} — odbierz nagrodę"),
            ("Посадити {0} рослин", "Plant {0} plants", "Posadź {0} roślin"),
            ("Зібрати {0} врожаїв", "Harvest {0} times", "Zbierz {0} plonów"),
            ("Полити {0} рослин", "Water {0} plants", "Podlej {0} roślin"),
            ("Заробити {0} монет на продажу", "Earn {0} coins from sales", "Zarób {0} monet ze sprzedaży"),
            ("Посадити «{0}» ×{1}", "Plant {0} ×{1}", "Posadź: {0} ×{1}"),
            ("Вилікувати рослину", "Cure a plant", "Wylecz roślinę"),
            ("Вилікувати {0} рослини", "Cure {0} plants", "Wylecz {0} rośliny"),

            // ── Колекції ─────────────────────────────────────────────────
            ("Сукуленти", "Succulents", "Sukulenty"),
            ("Квіти на підвіконні", "Windowsill flowers", "Kwiaty na parapecie"),
            ("Зелене листя", "Green leaves", "Zielone liście"),
            ("Тропіки вдома", "Tropics at home", "Tropiki w domu"),
            ("Рідкісні красуні", "Rare beauties", "Rzadkie piękności"),
            ("Колекція «{0}»: {1}/{2}", "Collection “{0}”: {1}/{2}", "Kolekcja „{0}”: {1}/{2}"),
            ("Колекцію «{0}» зібрано! +{1} кристал", "Collection “{0}” complete! +{1} gem", "Kolekcja „{0}” ukończona! +{1} kryształ"),

            // ── Дендрарій ────────────────────────────────────────────────
            ("Колекція тижня", "Collection of the week", "Kolekcja tygodnia"),
            ("Прогрес", "Progress", "Postęp"),
            ("Переглянути", "View", "Zobacz"),
            ("Відкрий більше видів, щоб отримати доступ до Колекції тижня.", "Discover more species to unlock the Collection of the week.", "Odkryj więcej gatunków, aby odblokować Kolekcję tygodnia."),
            ("Зібрано", "Collected", "Zebrano"),
            ("Особиста вітрина", "Personal showcase", "Osobista gablota"),
            ("Редагувати", "Edit", "Edytuj"),
            ("5 будь-яких відкритих рослин на показ друзям — без прогресу й нагороди.", "Any 5 discovered plants to show friends — no progress or reward.", "Dowolne 5 odkrytych roślin dla znajomych — bez postępu i nagrody."),
            ("Забрати нагороду", "Claim reward", "Odbierz nagrodę"),
            ("ще не відкрито", "not discovered yet", "jeszcze nieodkryte"),
            ("Нагороду отримано", "Reward claimed", "Nagroda odebrana"),
            ("Відкрито {0} з {1} видів · {2} колекцій", "Discovered {0} of {1} species · {2} collections", "Odkryto {0} z {1} gatunków · {2} kolekcji"),
            ("Забери до кінця тижня", "Claim before the week ends", "Odbierz do końca tygodnia"),

            // ── Лабораторія ──────────────────────────────────────────────
            ("Швидкість росту", "Growth speed", "Szybkość wzrostu"),
            ("менше часу до врожаю", "less time to harvest", "krócej do zbioru"),
            ("Здоров'я", "Health", "Zdrowie"),
            ("менше хвороб і шкідників", "fewer diseases and pests", "mniej chorób i szkodników"),
            ("Врожайність", "Yield", "Plonowanie"),
            ("більше прибутку з рослини", "more profit per plant", "większy zysk z rośliny"),
            ("час", "time", "czas"),
            ("хвороба", "disease", "choroba"),
            ("швидше", "faster", "szybciej"),
            ("віднов.", "recovery", "regener."),
            ("імунітет", "immunity", "odporność"),
            ("до шкідн.", "to pests", "na szkodn."),
            ("ціна", "price", "cena"),
            ("врожай", "harvest", "plon"),
            ("Дослідити", "Research", "Zbadaj"),
            ("Прискорити · {0}", "Speed up · {0}", "Przyspiesz · {0}"),
            ("Усі рівні гілки завершено", "All levels of this branch are done", "Wszystkie poziomy gałęzi ukończone"),
            ("Спочатку заверши поточне дослідження", "Finish the current research first", "Najpierw ukończ bieżące badanie"),
            ("Недостатньо монет", "Not enough coins", "Za mało monet"),
            ("Недостатньо кристалів", "Not enough gems", "Za mało kryształów"),
            ("Рівень {0} доступний", "Level {0} available", "Poziom {0} dostępny"),
            ("Рівень {0} · залишилось {1}", "Level {0} · {1} left", "Poziom {0} · zostało {1}"),

            // ── Профіль ──────────────────────────────────────────────────
            ("Садівник", "Gardener", "Ogrodnik"),
            ("Садівник-новачок", "Novice gardener", "Początkujący ogrodnik"),
            ("Досвідчений садівник", "Skilled gardener", "Doświadczony ogrodnik"),
            ("Золотий садівник", "Golden gardener", "Złoty ogrodnik"),
            ("Легендарний садівник", "Legendary gardener", "Legendarny ogrodnik"),
            ("Нове ім'я", "New name", "Nowe imię"),
            ("Ім'я...", "Name...", "Imię..."),
            ("Скасувати", "Cancel", "Anuluj"),
            ("Зберегти", "Save", "Zapisz"),
            ("Змінити", "Change", "Zmień"),
            ("Іконки аватара", "Avatar icons", "Ikony awatara"),
            ("Рамки профілю", "Profile frames", "Ramki profilu"),
            ("{0} з {1}", "{0} of {1}", "{0} z {1}"),
            ("{0} / {1} XP до {2} рівня", "{0} / {1} XP to level {2}", "{0} / {1} XP do poziomu {2}"),
            ("{0} токен зміни імені", "{0} rename token", "{0} żeton zmiany imienia"),
            ("{0} токени зміни імені", "{0} rename tokens", "{0} żetony zmiany imienia"),
            ("Заблоковано: {0}", "Locked: {0}", "Zablokowane: {0}"),
            ("Ще не відкрито", "Not unlocked yet", "Jeszcze nieodblokowane"),
            ("Потрібен токен зміни імені", "A rename token is required", "Potrzebny żeton zmiany imienia"),
            ("Введи ім'я", "Enter a name", "Wpisz imię"),
            ("Скоро", "Soon", "Wkrótce"),
            ("Сіра", "Grey", "Szara"),
            ("Зелена", "Green", "Zielona"),
            ("Золота", "Gold", "Złota"),
            ("Іскриста", "Sparkling", "Iskrząca"),
            ("Легендарна колекція", "Legendary collection", "Legendarna kolekcja"),
            ("Завдання тижня {0}", "Weekly task {0}", "Zadanie tygodnia {0}"),

            // ── Push-сповіщення ──────────────────────────────────────────
            ("{0} дозріла!", "{0} is ready!", "{0} jest gotowa!"),
            ("Збери урожай і посади нову рослину", "Harvest it and plant a new one", "Zbierz plon i posadź nową roślinę"),
            ("Усі рослини дозріли", "All plants are ready", "Wszystkie rośliny są gotowe"),
            ("Сад чекає на збір урожаю", "Your garden is waiting to be harvested", "Ogród czeka na zbiór plonów"),
            ("{0} захворіла", "{0} got sick", "{0} zachorowała"),
            ("Поки рослина хворіє, вона не росте — загляни в сад", "A sick plant doesn't grow — check your garden", "Chora roślina nie rośnie — zajrzyj do ogrodu"),
            ("Рослина чекає на лікування", "A plant needs treatment", "Roślina czeka na leczenie"),
            ("Вилікуй її, щоб вона знову росла", "Cure it so it grows again", "Wylecz ją, aby znowu rosła"),
            ("Нагорода дня чекає", "Your daily reward is waiting", "Nagroda dnia czeka"),
            ("Заходь забрати нагороду дня {0} і нові завдання", "Come claim your day {0} reward and new tasks", "Wpadnij po nagrodę dnia {0} i nowe zadania"),
        };
    }
}
