namespace PlantBreeding.Localization
{
    /// <summary>
    /// Таблиця перекладів: (українською — як у коді/сценах, English, Polski).
    /// {0},{1}… — місця для чисел/назв (перекладаються рекурсивно).
    /// Нова фраза в грі → додати рядок сюди; без перекладу текст лишається українським
    /// (у редакторі LocalizationApplier пише такі тексти в консоль).
    /// </summary>
    public static class LocTable
    {
        public static readonly (string uk, string en, string pl)[] Entries =
        {
            // ── Навігація, шапка, заголовки ───────────────────────────────
            ("Сад", "Garden", "Ogród"),
            ("Лабораторія", "Laboratory", "Laboratorium"),
            ("Дендрарій", "Arboretum", "Arboretum"),
            ("Крамниця", "Shop", "Sklep"),
            ("Мій сад", "My garden", "Mój ogród"),
            ("Посадка", "Planting", "Sadzenie"),
            ("Дослідження", "Research", "Badania"),
            ("Колекції", "Collections", "Kolekcje"),
            ("ростуть", "growing", "rośnie"),
            ("готові", "ready", "gotowe"),
            ("РІВЕНЬ {0} · {1}/{2} XP", "LEVEL {0} · {1}/{2} XP", "POZIOM {0} · {1}/{2} XP"),
            ("РІВЕНЬ {0}", "LEVEL {0}", "POZIOM {0}"),

            // ── Налаштування ─────────────────────────────────────────────
            ("Налаштування", "Settings", "Ustawienia"),
            ("Тема", "Theme", "Motyw"),
            ("ТЕМА", "THEME", "MOTYW"),
            ("Мова", "Language", "Język"),
            ("МОВА", "LANGUAGE", "JĘZYK"),
            ("Темна", "Dark", "Ciemny"),
            ("Світла", "Light", "Jasny"),
            ("Як у системі", "System", "Systemowy"),

            // ── Грядка ───────────────────────────────────────────────────
            ("Посадити", "Plant", "Posadź"),
            ("Заблоковано", "Locked", "Zablokowane"),
            ("Росте", "Growing", "Rośnie"),
            ("Готово", "Ready", "Gotowe"),
            ("Полити", "Water", "Podlej"),
            ("Рослина", "Plant", "Roślina"),
            ("Рівень {0}\nабо {1} монет", "Level {0}\nor {1} coins", "Poziom {0}\nlub {1} monet"),
            ("Рівень {0}", "Level {0}", "Poziom {0}"),
            ("Зібрати все · {0}", "Harvest all · {0}", "Zbierz wszystko · {0}"),
            ("{0} год {1} хв", "{0} h {1} min", "{0} godz. {1} min"),
            ("{0} год", "{0} h", "{0} godz."),
            ("{0} хв", "{0} min", "{0} min"),
            ("{0} с", "{0} s", "{0} s"),
            ("<1 хв", "<1 min", "<1 min"),

            // ── Рослини ──────────────────────────────────────────────────
            ("Фіалка", "African violet", "Fiołek afrykański"),
            ("Кактус", "Cactus", "Kaktus"),
            ("Алое", "Aloe", "Aloes"),
            ("Хлорофітум", "Spider plant", "Zielistka"),
            ("Сансев'єрія", "Snake plant", "Sansewieria"),
            ("Заміокулькас", "ZZ plant", "Zamiokulkas"),
            ("Епіпремнум", "Pothos", "Epipremnum"),
            ("Спатифілум", "Peace lily", "Skrzydłokwiat"),
            ("Фікус Бенджаміна", "Weeping fig", "Figowiec benjamina"),
            ("Бегонія", "Begonia", "Begonia"),
            ("Калатея", "Calathea", "Kalatea"),
            ("Пеларгонія", "Geranium", "Pelargonia"),
            ("Антуріум", "Anthurium", "Anturium"),
            ("Монстера", "Monstera", "Monstera"),
            ("Гібіскус", "Hibiscus", "Hibiskus"),
            ("Азалія", "Azalea", "Azalia"),
            ("Фікус ліровидний", "Fiddle-leaf fig", "Figowiec dębolistny"),
            ("Гарденія", "Gardenia", "Gardenia"),
            ("Стреліція", "Bird of paradise", "Strelicja"),
            ("Орхідея", "Orchid", "Storczyk"),

            // ── Горщики ──────────────────────────────────────────────────
            ("Пластиковий", "Plastic", "Plastikowa"),
            ("Теракотовий", "Terracotta", "Terakotowa"),
            ("Керамічний", "Ceramic", "Ceramiczna"),
            ("Плетене кашпо", "Wicker basket", "Wiklinowa osłonka"),
            ("Бетонний", "Concrete", "Betonowa"),
            ("Латунний", "Brass", "Mosiężna"),
            ("Мармуровий", "Marble", "Marmurowa"),
            ("без бонусу", "no bonus", "bez bonusu"),
            ("{0}% часу росту", "{0}% grow time", "{0}% czasu wzrostu"),
            ("полив рідше на {0}%", "water {0}% less often", "podlewanie o {0}% rzadziej"),
            ("{0}% ціна продажу", "{0}% sell price", "{0}% ceny sprzedaży"),
            ("{0}% ціна", "{0}% price", "{0}% ceny"),
            ("{0}% хвороб", "{0}% diseases", "{0}% chorób"),

            // ── Посадка ──────────────────────────────────────────────────
            ("Оберіть рослину", "Choose a plant", "Wybierz roślinę"),
            ("Оберіть горщик", "Choose a pot", "Wybierz doniczkę"),
            ("Добриво", "Fertilizer", "Nawóz"),
            ("інвентар", "inventory", "ekwipunek"),
            ("останній обраний", "last used", "ostatnio wybrana"),
            ("опційно", "optional", "opcjonalnie"),
            ("Оберіть рослину для прогнозу", "Choose a plant to see the forecast", "Wybierz roślinę, aby zobaczyć prognozę"),
            ("год", "h", "godz."),
            ("монет", "coins", "monet"),
            ("базовий", "base", "bazowy"),
            ("з рівня {0}", "from level {0}", "od poziomu {0}"),
            ("×{0} насіння", "×{0} seeds", "×{0} nasion"),
            ("Купити · {0} монет", "Buy · {0} coins", "Kup · {0} monet"),
            ("<color=#{0}>Купити · {1}</color>", "<color=#{0}>Buy · {1}</color>", "<color=#{0}>Kup · {1}</color>"),
            ("Купити · {0}", "Buy · {0}", "Kup · {0}"),
            ("Лише зі схрещування", "Breeding only", "Tylko z krzyżowania"),
            ("Посадити {0}", "Plant: {0}", "Posadź: {0}"),
            ("{0}% модиф.", "{0}% mod.", "{0}% mod."),
            ("{0}% горщик", "{0}% pot", "{0}% doniczka"),
            ("+полив до 30%", "+watering up to 30%", "+podlewanie do 30%"),
            ("Без добрива", "No fertilizer", "Bez nawozu"),
            ("за замовчуванням", "default", "domyślnie"),
            ("Ріст-буст", "Grow boost", "Przyspieszacz"),
            ("-30% часу росту", "-30% grow time", "-30% czasu wzrostu"),
            ("{0} монет", "{0} coins", "{0} monet"),

            // ── Урожай, рівні, грядки (тости) ────────────────────────────
            ("{0}: +{1} монет (подвійний урожай!)", "{0}: +{1} coins (double harvest!)", "{0}: +{1} monet (podwójny plon!)"),
            ("{0}: +{1} монет (догляд +{2}%)", "{0}: +{1} coins (care +{2}%)", "{0}: +{1} monet (pielęgnacja +{2}%)"),
            ("{0}: +{1} монет", "{0}: +{1} coins", "{0}: +{1} monet"),
            ("Перший урожай! Бонус +{0} монет — купи нове насіння", "First harvest! Bonus +{0} coins — buy new seeds", "Pierwszy plon! Bonus +{0} monet — kup nowe nasiona"),
            ("Рівень {0}! +{1} монет", "Level {0}! +{1} coins", "Poziom {0}! +{1} monet"),
            ("нове насіння: {0}", "new seeds: {0}", "nowe nasiona: {0}"),
            ("нова грядка", "new plot", "nowa grządka"),
            ("Грядка відкриється на рівні {0}", "Plot unlocks at level {0}", "Grządka odblokuje się na poziomie {0}"),
            ("Потрібно {0} монет (або рівень {1})", "Need {0} coins (or level {1})", "Potrzeba {0} monet (lub poziom {1})"),
            ("Нову грядку відкрито!", "New plot unlocked!", "Nowa grządka odblokowana!"),
            ("Зібрано {0} {1}: +{2} монет", "Harvested {0} {1}: +{2} coins", "Zebrano {0} {1}: +{2} monet"),
            ("рослин", "plants", "roślin"),
            ("рослину", "plant", "roślinę"),
            ("рослини", "plants", "rośliny"),
            ("Полито! +{0}% до ціни врожаю", "Watered! +{0}% to harvest price", "Podlano! +{0}% do ceny plonu"),
            ("Тапни порожню грядку й посади фіалку — вона виросте за 3 хвилини",
                "Tap an empty plot and plant a violet — it grows in 3 minutes",
                "Dotknij pustej grządki i posadź fiołek — wyrośnie w 3 minuty"),

            // ── Прискорення ──────────────────────────────────────────────
            ("{0}: {1} → {2} (−{3} крист.)", "{0}: {1} → {2} (−{3} gems)", "{0}: {1} → {2} (−{3} kryszt.)"),
            ("Рослина дорастає в 10 разів швидше: лишається 10% часу. Один раз на посадку.",
                "The plant grows 10× faster: only 10% of the time remains. Once per planting.",
                "Roślina rośnie 10× szybciej: zostaje 10% czasu. Raz na sadzenie."),
            ("До врожаю: {0} → {1}", "Until harvest: {0} → {1}", "Do zbioru: {0} → {1}"),
            ("До врожаю: {0}", "Until harvest: {0}", "Do zbioru: {0}"),
            ("У тебе: {0} {1}", "You have: {0} {1}", "Masz: {0} {1}"),
            ("Уже прискорено", "Already sped up", "Już przyspieszono"),
            ("Прискорити ×10 · {0} {1}", "Speed up ×10 · {0} {1}", "Przyspiesz ×10 · {0} {1}"),
            ("Потрібно {0} {1} — купити", "Need {0} {1} — buy", "Potrzeba {0} {1} — kup"),
            ("кристалів", "gems", "kryształów"),
            ("кристал", "gem", "kryształ"),
            ("кристали", "gems", "kryształy"),

            // ── Крамниця ─────────────────────────────────────────────────
            ("Кристали прискорюють ріст рослини в 10 разів", "Gems make a plant grow 10× faster", "Kryształy przyspieszają wzrost rośliny 10×"),
            ("Тестовий режим: оплата ще не підключена, кристали нараховуються одразу.",
                "Test mode: payments are not connected yet, gems are added instantly.",
                "Tryb testowy: płatności nie są jeszcze podłączone, kryształy dodawane są od razu."),
            ("Оплата ще не підключена — Крамниця запрацює незабаром", "Payments are not connected yet — the Shop is coming soon", "Płatności nie są jeszcze podłączone — sklep wkrótce"),
            ("+{0} кристалів (тестова покупка, оплата не підключена)", "+{0} gems (test purchase, payments not connected)", "+{0} kryształów (zakup testowy, płatności niepodłączone)"),
            ("{0} грн", "UAH {0}", "{0} UAH"),
            ("вигідно", "best value", "opłacalne"),
            ("Закрити", "Close", "Zamknij"),

            // ── Хвороби й лікування ──────────────────────────────────────
            ("Тля", "Aphids", "Mszyce"),
            ("Павутинний кліщ", "Spider mites", "Przędziorki"),
            ("Борошниста роса", "Powdery mildew", "Mączniak"),
            ("Хлороз", "Chlorosis", "Chloroza"),
            ("Зелені крапки на листі. Прибери їх — тапай по листочках.", "Green dots on the leaves. Remove them — tap the leaves.", "Zielone kropki na liściach. Usuń je — stukaj w liście."),
            ("Павутинка між листками. Обприскай листя — тапай, поки не зникне.", "Webbing between the leaves. Spray the leaves — tap until it's gone.", "Pajęczyna między liśćmi. Spryskaj liście — stukaj, aż zniknie."),
            ("Білий наліт на листі — грибок. Потрібен фунгіцид.", "White coating on the leaves — a fungus. Needs a fungicide.", "Biały nalot na liściach — grzyb. Potrzebny fungicyd."),
            ("Листя жовтіє — бракує заліза. Потрібне залізне добриво.", "Leaves turn yellow — iron deficiency. Needs iron fertilizer.", "Liście żółkną — brakuje żelaza. Potrzebny nawóz żelazowy."),
            ("Фунгіцид", "Fungicide", "Fungicyd"),
            ("фунгіцид", "fungicide", "fungicyd"),
            ("Залізне добриво", "Iron fertilizer", "Nawóz żelazowy"),
            ("залізне добриво", "iron fertilizer", "nawóz żelazowy"),
            ("Поки рослина хворіє, вона не росте.", "While the plant is sick, it doesn't grow.", "Dopóki roślina choruje, nie rośnie."),
            ("Прибрати · ще {0} {1}", "Remove · {0} more {1}", "Usuń · jeszcze {0} {1}"),
            ("{0} · {1} монет", "{0} · {1} coins", "{0} · {1} monet"),
            ("{0}: потрібно {1} монет", "{0}: need {1} coins", "{0}: potrzeba {1} monet"),
            ("тапів", "taps", "stuknięć"),
            ("тап", "tap", "stuknięcie"),
            ("тапи", "taps", "stuknięcia"),
            ("{0}: прибрано! {1} знову росте", "{0}: removed! {1} is growing again", "{0}: usunięto! {1} znowu rośnie"),
            ("Потрібно {0} монет на {1}", "Need {0} coins for {1}", "Potrzeba {0} monet na {1}"),
            ("{0} подіяв — {1} знову росте (−{2} монет)", "{0} worked — {1} is growing again (−{2} coins)", "{0} zadziałał — {1} znowu rośnie (−{2} monet)"),

            // ── Завдання дня, вхід, скриня ───────────────────────────────
            ("Завдання дня", "Daily tasks", "Zadania dnia"),
            ("Завдання", "Task", "Zadanie"),
            ("Стрік входів: {0} дн. · нові завдання щодня опівночі", "Login streak: {0} d · new tasks every midnight", "Seria logowań: {0} dn. · nowe zadania co północ"),
            ("Заходь завтра — почнеться стрік щоденних нагород", "Come back tomorrow to start a daily reward streak", "Wróć jutro — zacznie się seria codziennych nagród"),
            ("Нагорода за вхід · день {0} з 7", "Login reward · day {0} of 7", "Nagroda za logowanie · dzień {0} z 7"),
            ("Завтра: {0}", "Tomorrow: {0}", "Jutro: {0}"),
            ("Отримано. Завтра: {0}", "Claimed. Tomorrow: {0}", "Odebrano. Jutro: {0}"),
            ("Завтра", "Tomorrow", "Jutro"),
            ("Забрати", "Claim", "Odbierz"),
            ("Отримано", "Claimed", "Odebrano"),
            ("В процесі", "In progress", "W toku"),
            ("Відкрити", "Open", "Otwórz"),
            ("Відкрито", "Opened", "Otwarto"),
            ("+{0} монет", "+{0} coins", "+{0} monet"),
            ("+{0} XP", "+{0} XP", "+{0} XP"),
            ("+{0} насіння «{1}»", "+{0} {1} seeds", "+{0} nasion: {1}"),
            ("Нагороду дня {0} отримано: {1}", "Day {0} reward claimed: {1}", "Nagroda dnia {0} odebrana: {1}"),
            ("Скриню дня відкрито. Нові завдання — завтра!", "Daily chest opened. New tasks tomorrow!", "Skrzynia dnia otwarta. Nowe zadania jutro!"),
            ("Скриня дня: виконай усі завдання → +{0} монет", "Daily chest: finish all tasks → +{0} coins", "Skrzynia dnia: wykonaj wszystkie zadania → +{0} monet"),
            ("Скриня дня: +{0} монет", "Daily chest: +{0} coins", "Skrzynia dnia: +{0} monet"),
            ("+{0} XP. Нові завдання — завтра!", "+{0} XP. New tasks tomorrow!", "+{0} XP. Nowe zadania jutro!"),
            ("Завдання виконано: {0} — забери нагороду", "Task complete: {0} — claim your reward", "Zadanie wykonane: {0} — odbierz nagrodę"),
            ("Посадити {0} рослин", "Plant {0} plants", "Posadź {0} roślin"),
            ("Зібрати {0} врожаїв", "Harvest {0} times", "Zbierz {0} plonów"),
            ("Полити {0} рослин", "Water {0} plants", "Podlej {0} roślin"),
            ("Заробити {0} монет на продажу", "Earn {0} coins from sales", "Zarób {0} monet ze sprzedaży"),
            ("Посадити «{0}» ×{1}", "Plant {0} ×{1}", "Posadź: {0} ×{1}"),
            ("Вилікувати рослину", "Cure a plant", "Wylecz roślinę"),
            ("Вилікувати {0} рослини", "Cure {0} plants", "Wylecz {0} rośliny"),

            // ── Колекції ─────────────────────────────────────────────────
            ("Сукуленти", "Succulents", "Sukulenty"),
            ("Квіти на підвіконні", "Windowsill flowers", "Kwiaty na parapecie"),
            ("Зелене листя", "Green leaves", "Zielone liście"),
            ("Тропіки вдома", "Tropics at home", "Tropiki w domu"),
            ("Рідкісні красуні", "Rare beauties", "Rzadkie piękności"),
            ("Колекція «{0}»: {1}/{2}", "Collection “{0}”: {1}/{2}", "Kolekcja „{0}”: {1}/{2}"),
            ("Ботанік", "Botanist", "Botanik"),
            ("Лікар рослин", "Plant doctor", "Lekarz roślin"),
            ("Колекція горщиків", "Pot collection", "Kolekcja doniczek"),
            ("Ідеальний догляд", "Perfect care", "Idealna pielęgnacja"),
            ("Садівник-ветеран", "Veteran gardener", "Ogrodnik-weteran"),
            ("Гончар", "Potter", "Garncarz"),
            ("Ветеран", "Veteran", "Weteran"),
            ("Колекцію «{0}» зібрано! Забери нагороду в Дендрарії", "Collection “{0}” complete! Claim your reward in the Arboretum", "Kolekcja „{0}” ukończona! Odbierz nagrodę w Arboretum"),
            ("Колекцію тижня зібрано! Забери нагороду в Дендрарії", "Collection of the week complete! Claim your reward in the Arboretum", "Kolekcja tygodnia ukończona! Odbierz nagrodę w Arboretum"),
            ("Колекція тижня: {0}/{1}", "Collection of the week: {0}/{1}", "Kolekcja tygodnia: {0}/{1}"),
            ("Колекція «{0}»", "“{0}” collection", "Kolekcja „{0}”"),
            ("1 кристал", "1 gem", "1 kryształ"),
            ("{0} кристали", "{0} gems", "{0} kryształy"),
            ("аватар «{0}»", "avatar “{0}”", "awatar „{0}”"),
            ("рамка «{0}»", "frame “{0}”", "ramka „{0}”"),
            ("горщик «{0}»", "pot “{0}”", "doniczka „{0}”"),
            ("титул «{0}»", "title “{0}”", "tytuł „{0}”"),
            ("{0} насіння «{1}»", "{0} “{1}” seeds", "{0} nasion „{1}”"),
            ("ці види просять води рідше на {0}%", "these species need water {0}% less often", "te gatunki potrzebują wody o {0}% rzadziej"),
            ("+{0}% ціна продажу цих видів", "+{0}% sell price for these species", "+{0}% ceny sprzedaży tych gatunków"),
            ("−{0}% хвороб цих видів", "−{0}% diseases for these species", "−{0}% chorób tych gatunków"),
            ("+{0}% XP за ці види", "+{0}% XP for these species", "+{0}% XP za te gatunki"),
            ("полив +{0}% до ціни замість +{1}%", "watering +{0}% to price instead of +{1}%", "podlewanie +{0}% do ceny zamiast +{1}%"),
            ("Невибагливі рослини, що запасають воду в листі.", "Hardy plants that store water in their leaves.", "Niewymagające rośliny magazynujące wodę w liściach."),
            ("Квітучі рослини для світлого підвіконня.", "Flowering plants for a bright windowsill.", "Kwitnące rośliny na jasny parapet."),
            ("Декоративно-листяні рослини — зелень на весь рік.", "Foliage plants — green all year round.", "Rośliny liściaste — zieleń przez cały rok."),
            ("Великі тропічні рослини з яскравим листям і квітами.", "Large tropical plants with bright leaves and flowers.", "Duże tropikalne rośliny o jaskrawych liściach i kwiatach."),
            ("Найвибагливіші рослини гри — вершина садівника.", "The most demanding plants in the game — a gardener's peak.", "Najbardziej wymagające rośliny w grze — szczyt ogrodnika."),
            ("Збери всі 5 тематичних колекцій.", "Complete all 5 themed collections.", "Ukończ wszystkie 5 kolekcji tematycznych."),
            ("Вилікуй кожну хворобу і прожени кожного шкідника хоч раз.", "Cure every disease and chase off every pest at least once.", "Wylecz każdą chorobę i przegoń każdego szkodnika choć raz."),
            ("Купи всі горщики за монети.", "Buy every pot for coins.", "Kup wszystkie doniczki za monety."),
            ("Виростай кожен вид, не пропустивши жодного поливу.", "Grow every species without missing a single watering.", "Wyhoduj każdy gatunek, nie pomijając żadnego podlewania."),
            ("Збери врожай кожного виду 10 разів.", "Harvest every species 10 times.", "Zbierz plon każdego gatunku 10 razy."),
            ("Виростай кожен вид хоч раз — слот заповнюється після першого врожаю.", "Grow each species at least once — the slot fills after the first harvest.", "Wyhoduj każdy gatunek choć raz — miejsce wypełnia się po pierwszym zbiorze."),
            ("Слот заповнюється, щойно зібрано відповідну колекцію (нагороду забирати не обов'язково).", "A slot fills as soon as that collection is complete (claiming its reward isn't required).", "Miejsce wypełnia się, gdy dana kolekcja jest ukończona (odbiór nagrody nie jest wymagany)."),
            ("Хвороби з'являються з 3-го рівня на рослинах, що ростуть довше 15 хвилин.", "Diseases appear from level 3 on plants that grow longer than 15 minutes.", "Choroby pojawiają się od 3. poziomu na roślinach rosnących dłużej niż 15 minut."),
            ("Горщики купуються на екрані Посадки, секція «Горщик».", "Pots are bought on the Planting screen, “Pot” section.", "Doniczki kupuje się na ekranie Sadzenia, sekcja „Doniczka”."),
            ("Поливай щоразу, коли рослина просить води. Прискорення за кристали скорочує час для поливів.", "Water every time a plant asks for it. Speeding up with gems leaves less time for watering.", "Podlewaj za każdym razem, gdy roślina prosi o wodę. Przyspieszenie za kryształy skraca czas na podlewanie."),
            ("Рахуються врожаї, зібрані після появи цієї колекції в грі.", "Harvests count from the moment this collection appeared in the game.", "Liczą się plony zebrane po pojawieniu się tej kolekcji w grze."),
            ("Бамбуковий", "Bamboo", "Bambusowa"),
            ("{0}% XP", "{0}% XP", "{0}% XP"),

            // ── Дендрарій ────────────────────────────────────────────────
            ("Колекція тижня", "Collection of the week", "Kolekcja tygodnia"),
            ("Прогрес", "Progress", "Postęp"),
            ("Переглянути", "View", "Zobacz"),
            ("Відкрий більше видів, щоб отримати доступ до Колекції тижня.", "Discover more species to unlock the Collection of the week.", "Odkryj więcej gatunków, aby odblokować Kolekcję tygodnia."),
            ("Зібрано", "Collected", "Zebrano"),
            ("Особиста вітрина", "Personal showcase", "Osobista gablota"),
            ("Редагувати", "Edit", "Edytuj"),
            ("5 будь-яких відкритих рослин на показ друзям — без прогресу й нагороди.", "Any 5 discovered plants to show friends — no progress or reward.", "Dowolne 5 odkrytych roślin dla znajomych — bez postępu i nagrody."),
            ("Забрати нагороду", "Claim reward", "Odbierz nagrodę"),
            ("ще не відкрито", "not discovered yet", "jeszcze nieodkryte"),
            ("Нагороду отримано", "Reward claimed", "Nagroda odebrana"),
            ("Забери до кінця тижня", "Claim before the week ends", "Odbierz do końca tygodnia"),
            ("Відкрито {0} з {1} видів · зібрано {2} з {3} колекцій", "Discovered {0} of {1} species · completed {2} of {3} collections", "Odkryto {0} z {1} gatunków · ukończono {2} z {3} kolekcji"),
            ("Усі", "All", "Wszystkie"),
            ("Тематичні", "Themed", "Tematyczne"),
            ("Майстерність", "Mastery", "Mistrzostwo"),
            ("Нагорода: {0}", "Reward: {0}", "Nagroda: {0}"),
            ("Отримано: {0}", "Claimed: {0}", "Odebrano: {0}"),
            ("Забрати нагороду · ще {0}", "Claim reward · {0} to go", "Odbierz nagrodę · jeszcze {0}"),
            ("⏱ {0} дн", "⏱ {0} d", "⏱ {0} dni"),
            ("Колекція тижня · {0} дн", "Collection of the week · {0} d", "Kolekcja tygodnia · {0} dni"),
            ("Збери врожай кожного з цих видів до кінця тижня.", "Harvest each of these species before the week ends.", "Zbierz plon każdego z tych gatunków do końca tygodnia."),
            ("Збери врожай кожного з цих видів до кінця тижня. У понеділок — нові 4 види, прогрес обнуляється.", "Harvest each of these species before the week ends. On Monday — 4 new species and progress resets.", "Zbierz plon każdego z tych gatunków do końca tygodnia. W poniedziałek — 4 nowe gatunki, postęp się zeruje."),
            ("Види тижня обираються з тих, що ти вже відкривав.", "Weekly species are picked from the ones you've already discovered.", "Gatunki tygodnia są wybierane spośród już odkrytych."),
            ("зібрано {0}×", "harvested {0}×", "zebrano {0}×"),
            ("зібрано {0}/{1}", "harvested {0}/{1}", "zebrano {0}/{1}"),
            ("без пропусків", "no misses", "bez pominięć"),
            ("ще не вдалось", "not yet", "jeszcze nie"),
            ("вилікувано", "cured", "wyleczono"),
            ("ще не траплялось", "not encountered yet", "jeszcze nie wystąpiło"),
            ("куплено", "bought", "kupiono"),
            ("шкідник", "pest", "szkodnik"),
            ("звичайна", "common", "zwykła"),
            ("рідкісна", "rare", "rzadka"),
            ("епічна", "epic", "epicka"),
            ("легендарна", "legendary", "legendarna"),
            ("зібрано цього тижня", "harvested this week", "zebrano w tym tygodniu"),
            ("ще не зібрано", "not harvested yet", "jeszcze nie zebrano"),
            ("Паросток", "Sprout", "Kiełek"),
            ("Листок", "Leaf", "Liść"),
            ("Лікар", "Doctor", "Lekarz"),
            ("Золота лійка", "Golden watering can", "Złota konewka"),
            ("Троянда", "Rose", "Róża"),
            ("Сонце", "Sun", "Słońce"),
            ("Квіткова", "Floral", "Kwiatowa"),
            ("Роса", "Dew", "Rosa"),
            ("Мармурова", "Marble", "Marmurowa"),

            // ── Крамниця ─────────────────────────────────────────────────
            ("Набори", "Bundles", "Zestawy"),
            ("Кристали", "Gems", "Kryształy"),
            ("Монети", "Coins", "Monety"),
            ("Горщики", "Pots", "Doniczki"),
            ("Насіння", "Seeds", "Nasiona"),
            ("Грядки", "Beds", "Grządki"),
            ("Клуб", "Club", "Klub"),
            ("Підписка", "Subscription", "Subskrypcja"),
            ("Назавжди", "Forever", "Na zawsze"),
            ("Преміум-горщики", "Premium pots", "Doniczki premium"),
            ("Додаткові грядки", "Extra beds", "Dodatkowe grządki"),
            ("ОДИН РАЗ", "ONE TIME", "JEDNORAZOWO"),
            ("Стартовий", "Starter", "Startowy"),
            ("Садівник-профі", "Pro gardener", "Ogrodnik-profi"),
            ("Перші {0} дні гри", "First {0} days of play", "Pierwsze {0} dni gry"),
            ("Лишилось {0} дн {1} год", "{0} d {1} h left", "Zostało {0} d {1} godz"),
            ("Лишилось {0} год {1} хв", "{0} h {1} min left", "Zostało {0} godz {1} min"),
            ("{0} кристалів", "{0} gems", "{0} kryształów"),
            ("Кришталевий горщик", "Crystal pot", "Kryształowa doniczka"),
            ("Кришталевий", "Crystal", "Kryształowa"),
            ("Нефритовий", "Jade", "Nefrytowa"),
            ("Золотий", "Gold", "Złota"),
            ("20 кристалів + 1 500 монет + Кришталевий горщик", "20 gems + 1,500 coins + Crystal pot", "20 kryształów + 1 500 monet + Kryształowa doniczka"),
            ("80 кристалів + 5 000 монет + Нефритовий горщик", "80 gems + 5,000 coins + Jade pot", "80 kryształów + 5 000 monet + Nefrytowa doniczka"),
            ("≈ день гри", "≈ a day of play", "≈ dzień gry"),
            ("≈ 3 дні гри", "≈ 3 days of play", "≈ 3 dni gry"),
            ("≈ 9 днів гри", "≈ 9 days of play", "≈ 9 dni gry"),
            ("Вигідно", "Best value", "Najkorzystniej"),
            ("Набір насіння", "Seed pack", "Zestaw nasion"),
            // ── Насіннєва капсула ────────────────────────────────────────
            ("Насіннєва капсула", "Seed capsule", "Kapsuła nasion"),
            ("КАПСУЛА · ЗА КРИСТАЛИ", "CAPSULE · FOR GEMS", "KAPSUŁA · ZA KRYSZTAŁY"),
            ("3 насінини трьох різних рослин. Яких — дізнаєшся, коли відкриєш. Може випасти рослина вище твого рівня — її можна посадити одразу.",
             "3 seeds of three different plants. Which ones — you'll see when you open it. You may get a plant above your level — you can plant it right away.",
             "3 nasiona trzech różnych roślin. Jakich — zobaczysz po otwarciu. Może wypaść roślina powyżej twojego poziomu — możesz ją od razu posadzić."),
            ("{0} насінини трьох різних рослин — сюрприз", "{0} seeds of three different plants — a surprise", "{0} nasiona trzech różnych roślin — niespodzianka"),
            ("Сюрприз", "Surprise", "Niespodzianka"),
            ("Шанси для кожної насінини: {0}", "Odds for each seed: {0}", "Szanse dla każdego nasiona: {0}"),
            ("Звичайна {0}%", "Common {0}%", "Zwykła {0}%"),
            ("Рідкісна {0}%", "Rare {0}%", "Rzadka {0}%"),
            ("Епічна {0}%", "Epic {0}%", "Epicka {0}%"),
            ("Легендарна {0}%", "Legendary {0}%", "Legendarna {0}%"),
            ("Відкрити · {0} кристалів", "Open · {0} gems", "Otwórz · {0} kryształów"),
            ("Відкрити за {0} кристалів", "Open for {0} gems", "Otwórz za {0} kryształów"),
            ("Капсулу відкрито", "Capsule opened", "Kapsuła otwarta"),
            ("Бракує кристалів: потрібно {0}. Кристали є вище в Крамниці.", "Not enough gems: you need {0}. Gems are above in the Shop.", "Za mało kryształów: potrzeba {0}. Kryształy są wyżej w Sklepie."),
            ("{0} — звичайна", "{0} — common", "{0} — zwykła"),
            ("{0} — рідкісна", "{0} — rare", "{0} — rzadka"),
            ("{0} — епічна", "{0} — epic", "{0} — epicka"),
            ("{0} — легендарна", "{0} — legendary", "{0} — legendarna"),
            ("10 насінин найдорожчого з відкритих видів.", "10 seeds of the most expensive unlocked species.", "10 nasion najdroższego z odblokowanych gatunków."),
            ("Зараз: {0}", "Now: {0}", "Teraz: {0}"),
            ("7-ма грядка", "7th bed", "7. grządka"),
            ("8-ма грядка", "8th bed", "8. grządka"),
            ("{0} · після 7-ї", "{0} · after the 7th", "{0} · po 7."),
            ("Куплено", "Bought", "Kupiono"),
            ("Є", "Owned", "Masz"),
            ("Клуб садівника", "Gardener's club", "Klub ogrodnika"),
            ("{0} кристали щодня", "{0} gems daily", "{0} kryształy dziennie"),
            ("+{0}% монет з продажу", "+{0}% coins from sales", "+{0}% monet ze sprzedaży"),
            ("Рамка «Клуб»", "“Club” frame", "Ramka „Klub”"),
            ("{0} монет щодня", "{0} coins daily", "{0} monet dziennie"),
            ("Рамка «Клуб» і аватар «Сонце» — назавжди", "“Club” frame and “Sun” avatar — forever", "Ramka „Klub” i awatar „Słońce” — na zawsze"),
            ("{0} / місяць", "{0} / month", "{0} / miesiąc"),
            ("Ти в Клубі садівника", "You're in the Gardener's club", "Jesteś w Klubie ogrodnika"),
            ("Скасувати чи змінити підписку — у налаштуваннях App Store / Google Play.", "Cancel or change the subscription in App Store / Google Play settings.", "Anuluj lub zmień subskrypcję w ustawieniach App Store / Google Play."),
            ("Відновити покупки", "Restore purchases", "Przywróć zakupy"),
            ("Горщики з колекцій, аватари й рамки здобуваються тільки в грі.", "Collection pots, avatars and frames can only be earned in the game.", "Doniczki z kolekcji, awatary i ramki zdobywa się tylko w grze."),
            ("Редактор: тестовий магазин — покупки без оплати.", "Editor: test store — purchases without payment.", "Edytor: sklep testowy — zakupy bez płatności."),
            ("Купити за {0}", "Buy for {0}", "Kup za {0}"),
            ("Оплата…", "Paying…", "Płatność…"),
            ("Добре", "OK", "OK"),
            ("{0} додано.", "{0} added.", "Dodano: {0}."),
            ("{0} додано: {1}.", "{0} added: {1}.", "Dodano {0}: {1}."),
            ("Не вдалося", "Something went wrong", "Nie udało się"),
            ("Спробуй пізніше.", "Try again later.", "Spróbuj później."),
            ("Магазин недоступний. Перевір інтернет і спробуй пізніше.", "The store is unavailable. Check your connection and try again later.", "Sklep jest niedostępny. Sprawdź internet i spróbuj później."),
            ("Оплата не пройшла. Гроші не списано.", "The payment didn't go through. You were not charged.", "Płatność nie powiodła się. Nie pobrano opłaty."),
            ("Покупка чекає на схвалення. Товар з'явиться після підтвердження.", "The purchase is awaiting approval. The item will appear once it's approved.", "Zakup czeka na zatwierdzenie. Przedmiot pojawi się po zatwierdzeniu."),
            ("Покупки відновлено", "Purchases restored", "Zakupy przywrócone"),
            ("Не вдалося відновити: {0}", "Couldn't restore: {0}", "Nie udało się przywrócić: {0}"),
            ("Тестовий магазин: покупки вже збережені в грі", "Test store: purchases are already saved in the game", "Sklep testowy: zakupy są już zapisane w grze"),
            ("Клуб садівника: +{0} кристали сьогодні", "Gardener's club: +{0} gems today", "Klub ogrodnika: +{0} kryształy dzisiaj"),
            ("Клуб садівника: +{0} кристали і +{1} монет сьогодні", "Gardener's club: +{0} gems and +{1} coins today", "Klub ogrodnika: +{0} kryształy i +{1} monet dzisiaj"),
            ("Набір · один раз", "Bundle · one time", "Zestaw · jednorazowo"),
            ("Преміум-горщик · назавжди", "Premium pot · forever", "Doniczka premium · na zawsze"),
            ("Грядка · назавжди", "Bed · forever", "Grządka · na zawsze"),
            ("Ще одне місце в саду.", "One more spot in your garden.", "Jeszcze jedno miejsce w ogrodzie."),
            ("Прискорюють ріст рослини в 10 разів.", "Speed up plant growth 10×.", "Przyspieszają wzrost rośliny 10×."),
            ("На 10% більше, ніж у найменшому пакеті.", "10% more than the smallest pack.", "O 10% więcej niż w najmniejszym pakiecie."),
            ("На 25% більше, ніж у найменшому пакеті.", "25% more than the smallest pack.", "O 25% więcej niż w najmniejszym pakiecie."),
            ("Найвигідніший пакет.", "The best-value pack.", "Najkorzystniejszy pakiet."),
            ("Приблизно один день гри.", "About one day of play.", "Około jednego dnia gry."),
            ("Приблизно три дні гри.", "About three days of play.", "Około trzech dni gry."),
            ("Приблизно дев'ять днів гри.", "About nine days of play.", "Około dziewięciu dni gry."),
            ("−15% часу", "−15% time", "−15% czasu"),
            ("{0}-ма грядка в саду", "bed #{0} in the garden", "{0}. grządka w ogrodzie"),
            ("Щомісяця, скасувати можна будь-коли.", "Monthly, cancel any time.", "Co miesiąc, anuluj w dowolnym momencie."),
            ("Підписка «Клуб садівника» у Крамниці", "“Gardener's club” subscription in the Shop", "Subskrypcja „Klub ogrodnika” w Sklepie"),
            ("Клуб садівника в Крамниці", "Gardener's club in the Shop", "Klub ogrodnika w Sklepie"),
            ("3 кристали і 200 монет щодня · +10% монет з продажу · рамка «Клуб» і аватар «Сонце» назавжди. Щомісяця, скасувати можна будь-коли.",
             "3 gems and 200 coins daily · +10% coins from sales · “Club” frame and “Sun” avatar forever. Monthly, cancel anytime.",
             "3 kryształy i 200 monet dziennie · +10% monet ze sprzedaży · ramka „Klub” i awatar „Słońce” na zawsze. Co miesiąc, anuluj w każdej chwili."),

            // ── Лабораторія ──────────────────────────────────────────────
            ("Швидкість росту", "Growth speed", "Szybkość wzrostu"),
            ("менше часу до врожаю", "less time to harvest", "krócej do zbioru"),
            ("Здоров'я", "Health", "Zdrowie"),
            ("менше хвороб і шкідників", "fewer diseases and pests", "mniej chorób i szkodników"),
            ("Врожайність", "Yield", "Plonowanie"),
            ("більше прибутку з рослини", "more profit per plant", "większy zysk z rośliny"),
            ("Досвід", "Experience", "Doświadczenie"),
            ("більше XP з кожного врожаю", "more XP from every harvest", "więcej XP z każdego zbioru"),
            ("час", "time", "czas"),
            ("хвороба", "disease", "choroba"),
            ("швидше", "faster", "szybciej"),
            ("віднов.", "recovery", "regener."),
            ("імунітет", "immunity", "odporność"),
            ("до шкідн.", "to pests", "na szkodn."),
            ("ціна", "price", "cena"),
            ("врожай", "harvest", "plon"),
            ("Дослідити", "Research", "Zbadaj"),
            ("Прискорити · {0}", "Speed up · {0}", "Przyspiesz · {0}"),
            ("Усі рівні гілки завершено", "All levels of this branch are done", "Wszystkie poziomy gałęzi ukończone"),
            ("Спочатку заверши поточне дослідження", "Finish the current research first", "Najpierw ukończ bieżące badanie"),
            ("Недостатньо монет", "Not enough coins", "Za mało monet"),
            ("Недостатньо кристалів", "Not enough gems", "Za mało kryształów"),
            ("Рівень {0} доступний", "Level {0} available", "Poziom {0} dostępny"),
            ("Рівень {0} · залишилось {1}", "Level {0} · {1} left", "Poziom {0} · zostało {1}"),

            // ── Профіль ──────────────────────────────────────────────────
            ("Садівник", "Gardener", "Ogrodnik"),
            ("Садівник-новачок", "Novice gardener", "Początkujący ogrodnik"),
            ("Досвідчений садівник", "Skilled gardener", "Doświadczony ogrodnik"),
            ("Золотий садівник", "Golden gardener", "Złoty ogrodnik"),
            ("Легендарний садівник", "Legendary gardener", "Legendarny ogrodnik"),
            ("Нове ім'я", "New name", "Nowe imię"),
            ("Ім'я...", "Name...", "Imię..."),
            ("Скасувати", "Cancel", "Anuluj"),
            ("Зберегти", "Save", "Zapisz"),
            ("Змінити", "Change", "Zmień"),
            ("Іконки аватара", "Avatar icons", "Ikony awatara"),
            ("Рамки профілю", "Profile frames", "Ramki profilu"),
            ("{0} з {1}", "{0} of {1}", "{0} z {1}"),
            ("{0} / {1} XP до {2} рівня", "{0} / {1} XP to level {2}", "{0} / {1} XP do poziomu {2}"),
            ("{0} токен зміни імені", "{0} rename token", "{0} żeton zmiany imienia"),
            ("{0} токени зміни імені", "{0} rename tokens", "{0} żetony zmiany imienia"),
            ("Заблоковано: {0}", "Locked: {0}", "Zablokowane: {0}"),
            ("Ще не відкрито", "Not unlocked yet", "Jeszcze nieodblokowane"),
            ("Потрібен токен зміни імені", "A rename token is required", "Potrzebny żeton zmiany imienia"),
            ("Введи ім'я", "Enter a name", "Wpisz imię"),
            ("Скоро", "Soon", "Wkrótce"),
            ("Сіра", "Grey", "Szara"),
            ("Зелена", "Green", "Zielona"),
            ("Золота", "Gold", "Złota"),
            ("Іскриста", "Sparkling", "Iskrząca"),
            ("Легендарна колекція", "Legendary collection", "Legendarna kolekcja"),

            // ── Push-сповіщення ──────────────────────────────────────────
            ("{0} дозріла!", "{0} is ready!", "{0} jest gotowa!"),
            ("Збери урожай і посади нову рослину", "Harvest it and plant a new one", "Zbierz plon i posadź nową roślinę"),
            ("Усі рослини дозріли", "All plants are ready", "Wszystkie rośliny są gotowe"),
            ("Сад чекає на збір урожаю", "Your garden is waiting to be harvested", "Ogród czeka na zbiór plonów"),
            ("{0} захворіла", "{0} got sick", "{0} zachorowała"),
            ("Поки рослина хворіє, вона не росте — загляни в сад", "A sick plant doesn't grow — check your garden", "Chora roślina nie rośnie — zajrzyj do ogrodu"),
            ("Рослина чекає на лікування", "A plant needs treatment", "Roślina czeka na leczenie"),
            ("Вилікуй її, щоб вона знову росла", "Cure it so it grows again", "Wylecz ją, aby znowu rosła"),
            ("Нагорода дня чекає", "Your daily reward is waiting", "Nagroda dnia czeka"),
            ("Заходь забрати нагороду дня {0} і нові завдання", "Come claim your day {0} reward and new tasks", "Wpadnij po nagrodę dnia {0} i nowe zadania"),
        };
    }
}
